name: Unit Test Policies

##########################################
# Start the job on push for all branches #
##########################################

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "src/resources/Microsoft.Authorization/policyDefinitions/**.json"
  workflow_dispatch: {}

env:
  POLICY_DIR: "src/resources/Microsoft.Authorization/policyDefinitions/"

jobs:
  validate-policy-file:
    name: Validate Policy File
    runs-on: ubuntu-latest
    environment: csu-rw
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: true

      - name: Get List of Changed Files
        run: git diff HEAD^ $POLICY_DIR ${PATHS} -- HEAD $POLICY_DIR --name-only

  # validate-policy-deployment:
  #   name: Validate-Policy-Deployment
  #   runs-on: ubuntu-latest
  #   environment: csu-rw

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.event.pull_request.head.sha }}
  #         persist-credentials: true

  #     - name: Get List of Changed Files
  #       run: git diff HEAD^ $POLICY_DIR ${PATHS} -- HEAD $POLICY_DIR --name-only
